# Generated by Django 3.1.1 on 2020-09-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid_19_India',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('state', models.CharField(max_length=20)),
                ('confirmed_indian_national', models.IntegerField()),
                ('confirmed_foreign_national', models.IntegerField()),
                ('cured', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('confirmed', models.IntegerField()),
            ],
        ),
    ]
