# Generated by Django 3.1.1 on 2020-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_covid_19_india'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid_19_india',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
