# Generated by Django 3.1.1 on 2020-09-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200906_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid_19_india',
            name='confirmed',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='covid_19_india',
            name='confirmed_foreign_national',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='covid_19_india',
            name='confirmed_indian_national',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='covid_19_india',
            name='cured',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='covid_19_india',
            name='deaths',
            field=models.CharField(max_length=10),
        ),
    ]
