# Generated by Django 3.1.1 on 2020-09-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200906_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBedsIndia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('numPrimaryHealthCenters_HMIS', models.CharField(max_length=10)),
                ('numCommunityHealthCenters_HMIS', models.CharField(max_length=10)),
                ('numSubDistrictHospitals_HMIS', models.CharField(max_length=10)),
                ('numDistrictHospitals_HMIS', models.CharField(max_length=10)),
                ('totalPublicHealthFacilities_HMIS', models.CharField(max_length=10)),
                ('numPublicBeds_HMIS', models.CharField(max_length=10)),
                ('numRuralHospitals_NHP18', models.CharField(max_length=10)),
                ('numRuralBeds_NHP18', models.CharField(max_length=10)),
                ('numUrbanHospitals_NHP18', models.CharField(max_length=10)),
                ('numUrbanBeds_NHP18', models.CharField(max_length=10)),
            ],
        ),
    ]
