# Generated by Django 3.1.1 on 2020-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_icmrtestinglabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icmrtestinglabs',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
