# Generated by Django 3.1.1 on 2020-09-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200906_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icmrtestinglabs',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='icmrtestinglabs',
            name='lab',
            field=models.TextField(),
        ),
    ]
