# Generated by Django 3.1.1 on 2020-09-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200906_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('government_id', models.CharField(max_length=10)),
                ('diagnosed_date', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('detected_city', models.CharField(max_length=20)),
                ('detected_district', models.CharField(max_length=20)),
                ('detected_state', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=10)),
                ('current_status', models.CharField(max_length=10)),
                ('status_change_date', models.CharField(max_length=10)),
                ('notes', models.TextField()),
            ],
        ),
    ]
