# Generated by Django 3.1.1 on 2020-09-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200906_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population_India_Census2011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('population', models.CharField(max_length=10)),
                ('rural_population', models.CharField(max_length=10)),
                ('urban_population', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=20)),
                ('density', models.CharField(max_length=20)),
                ('gender_ratio', models.CharField(max_length=10)),
            ],
        ),
    ]
